export const portfolio = {
  resume: "/assets/pdf/resume-data-engineering.pdf",
  navigation: [
    { label: "Story", href: "#story" },
    { label: "Projects", href: "#projects" },
    { label: "Skills", href: "#skills" },
    { label: "Experience", href: "#experience" },
    { label: "Contact", href: "#contact" },
  ],
  contact: {
    email: "amiralidshiraz@gmail.com",
    github: "https://github.com/dankends",
    linkedin: "https://www.linkedin.com/in/amiralishiraz/",
  },
  metrics: [
    { value: "500+ TB", label: "Cumulative data processed across production pipelines" },
    { value: "60%", label: "Reduction in inconsistent records through validation" },
    { value: "45%", label: "Faster Power BI queries from optimized reporting layers" },
    { value: "30%", label: "Less manual data preparation through automation" },
  ],
  story: [
    {
      period: "2016 — 2021",
      title: "Understanding the signals",
      body: "Electrical engineering built my foundation in control systems, telemetry, signal processing, and the physical systems that generate operational data.",
      tags: ["Signals", "Control systems", "MATLAB", "Telemetry"],
    },
    {
      period: "2021 — 2024",
      title: "Learning at sensor scale",
      body: "At Polytechnique Montréal, I processed telemetry from more than 140,000 electric water heaters and shaped raw electrical signals into validated, analysis-ready time series.",
      tags: ["140K+ sensors", "Python", "SQL", "Spark", "Time series"],
    },
    {
      period: "2024 — Present",
      title: "Building production pipelines",
      body: "At Bright Bee Technology, I build ETL/ELT systems across APIs, JSON, spreadsheets, and operational databases with Python, PySpark, Databricks, and AWS.",
      tags: ["ETL/ELT", "Databricks", "AWS", "Data quality"],
    },
    {
      period: "Today",
      title: "Making data useful",
      body: "I connect governed models and reporting layers to analytics and machine learning workflows—so complex data becomes faster decisions and reliable products.",
      tags: ["Dimensional models", "Power BI", "ML-ready data", "AI"],
    },
  ],
  featuredProjects: [
    {
      type: "Lakehouse engineering",
      title: "Clinic Billing Lakehouse",
      summary: "A governed Databricks pipeline that turns raw clinic billing exports into dependable financial reporting models.",
      problem: "Fragmented billing exports need consistent structure before they can support trustworthy financial KPIs.",
      focus: "Medallion layers, incremental transformations, data modelling, and governed reporting tables.",
      result: "A Delta Lake star schema with analytics-ready KPI marts.",
      tags: ["Databricks", "Delta Live Tables", "PySpark", "Star schema"],
      href: "https://github.com/dankends/clinic-billing-lakehouse",
      status: "medallion / governed",
      architecture: [
        { type: "Source", label: "Billing exports" },
        { type: "Bronze", label: "Raw Delta" },
        { type: "Silver", label: "Validated" },
        { type: "Gold", label: "KPI marts" },
      ],
      quality: { title: "Quality at every layer", body: "Validation and governed transformations keep reporting logic traceable." },
    },
    {
      type: "Real-time health data",
      title: "Healthcare Vital Signs Platform",
      summary: "A streaming platform that structures patient vital events for analytics, machine learning features, and dashboard exports.",
      problem: "Vital-sign events arrive continuously and need validation before downstream clinical or analytical use.",
      focus: "Streaming ingestion, dimensional modelling, validation, and ML-ready feature preparation.",
      result: "A production-oriented design spanning Kinesis, Databricks, and Delta Lake.",
      tags: ["AWS Kinesis", "Databricks", "Delta Lake", "ML features"],
      href: "https://github.com/dankends/healthcare-vitals-pipeline",
      status: "streaming / validated",
      architecture: [
        { type: "Event", label: "Patient vitals" },
        { type: "Stream", label: "Kinesis" },
        { type: "Lakehouse", label: "Delta" },
        { type: "Serve", label: "ML + BI" },
      ],
      quality: { title: "Designed for sensitive data", body: "Validation gates separate malformed events before features or dashboards are produced." },
    },
    {
      type: "Industrial data platform",
      title: "Electrical Asset Data Pipeline",
      summary: "An end-to-end pipeline that turns mixed electrical asset files and alert feeds into structured, usable datasets.",
      problem: "CSV exports, JSON logs, inspection documents, and alerts arrive with inconsistent shapes and context.",
      focus: "Multi-format ingestion, standardization, validation, and analytics-ready transformation.",
      result: "Structured datasets prepared for asset analytics and machine learning.",
      tags: ["Python", "JSON", "Data validation", "Asset analytics"],
      href: "https://github.com/dankends/electrical-asset-data-pipeline",
      status: "multi-source / standardized",
      architecture: [
        { type: "Source", label: "Files + alerts" },
        { type: "Ingest", label: "Python" },
        { type: "Model", label: "Asset schema" },
        { type: "Use", label: "Analytics" },
      ],
      quality: { title: "Context preserved", body: "Source-specific checks protect asset identity and inspection traceability." },
    },
    {
      type: "Analytics engineering",
      title: "Customer Operations Warehouse",
      summary: "A Python and SQL pipeline that connects customer activity across sales, billing, usage, and support.",
      problem: "CRM leads, subscriptions, invoices, product events, and tickets live in disconnected operational systems.",
      focus: "Cross-source integration, warehouse modelling, quality checks, and rejected-record handling.",
      result: "One analytics layer for customer operations reporting.",
      tags: ["Python", "SQL", "Data warehouse", "Quality checks"],
      href: "https://github.com/dankends/customer-ops-analytics",
      status: "batch / analytics-ready",
      architecture: [
        { type: "Source", label: "CRM + billing" },
        { type: "Process", label: "Python + SQL" },
        { type: "Model", label: "Warehouse" },
        { type: "Serve", label: "Operations BI" },
      ],
      quality: { title: "Bad records stay visible", body: "Rejected-record handling preserves auditability instead of silently dropping data." },
    },
  ],
  archiveProjects: [
    { year: "2025", title: "DMFlix: Dagster + Snowflake + ML Embeddings", category: "Data / ML", href: "https://github.com/dankends/DMFlix-Dagster-Snowflake-ML-embeddings" },
    { year: "2025", title: "Permit Automation Agent with LangFlow & n8n", category: "Automation" },
    { year: "2025", title: "Multi-GPU Stable Diffusion Pipeline", category: "ML systems" },
    { year: "2025", title: "Clinical Pathway Prediction with MIMIC-IV", category: "Healthcare ML", href: "https://github.com/dankends/ClinicalTrajectoryPredictor" },
    { year: "2024", title: "Morningstar ETFs vs Mutual Funds", category: "Analytics", href: "https://github.com/dankends/morningstar-etfs-vs-mutual-funds" },
    { year: "2024", title: "Traffic Optimization with AWS IoT & ML", category: "IoT / ML", href: "https://github.com/dankends/traffic-optimization-AWS" },
    { year: "2024", title: "Coffee Production Analysis", category: "Analytics", href: "https://github.com/dankends/Coffee-Analysis" },
    { year: "2023", title: "Real-Time Disaster Sentiment on AWS", category: "Streaming NLP" },
    { year: "2023", title: "Monte Carlo Methods for Episodic Learning", category: "Reinforcement learning", href: "https://github.com/dankends/Reinforcement-Learning" },
    { year: "2022", title: "Temporal Difference Learning", category: "Reinforcement learning", href: "https://github.com/dankends/Reinforcement-Learning" },
    { year: "2021", title: "Bayesian Multi-Agent Estimation", category: "Statistical modelling" },
    { year: "2020", title: "Signal Processing & Digital Filtering", category: "Electrical engineering" },
  ],
  skills: [
    {
      kicker: "Build & transform",
      title: "Data engineering",
      body: "Designing dependable paths from raw source data to trusted, reusable models.",
      items: ["ETL/ELT", "PySpark", "Databricks", "Delta Lake", "Data pipelines", "Large-scale processing", "APIs", "Time-series data"],
    },
    {
      kicker: "Store & govern",
      title: "Platforms & modelling",
      body: "Structuring data so reporting, analytics, and ML teams can use it with confidence.",
      items: ["AWS S3", "AWS Glue", "Snowflake", "Star schemas", "Dimensional modelling", "Data quality", "Validation", "Lineage"],
    },
    {
      kicker: "Program & automate",
      title: "Engineering workflow",
      body: "Using code, orchestration, and version control to make repeatable systems easier to maintain.",
      items: ["Python", "SQL", "Dagster", "n8n", "Git", "GitHub", "CI/CD", "C++"],
    },
    {
      kicker: "Analyze & enable",
      title: "Analytics & AI support",
      body: "Preparing data and features for decisions, dashboards, and machine learning workflows.",
      items: ["Power BI", "Tableau", "Feature engineering", "Scikit-learn", "TensorFlow", "PyTorch", "Anomaly detection", "NLP"],
    },
  ],
  experience: [
    {
      company: "Bright Bee Technology",
      role: "Data Engineer",
      location: "Toronto, Canada",
      period: "Mar 2024 — Present",
      logo: "/assets/images/brightbee.jpeg",
      summary: "Building production data systems across structured and unstructured operational sources.",
      highlights: [
        "Reduced manual data preparation by 30% with scalable Python, PySpark, Databricks, and AWS workflows.",
        "Improved Power BI query performance by 45% through dimensional models and optimized SQL reporting layers.",
        "Reduced inconsistent records by 60% with automated validation and traceable rejected-record handling.",
      ],
      tags: ["Python", "SQL", "PySpark", "Databricks", "AWS", "Power BI"],
    },
    {
      company: "Polytechnique Montréal",
      role: "Research Assistant",
      location: "Montréal, Canada",
      period: "2021 — Sep 2024",
      logo: "/assets/images/polymtl.png",
      summary: "Transforming high-volume electrical telemetry into reproducible research and ML-ready datasets.",
      highlights: [
        "Processed and modelled telemetry from more than 140,000 electric water heater sensors.",
        "Combined MATLAB/Simulink experiments with Python-based statistical and machine learning methods.",
        "Integrated monitoring devices with SCADA/EPMS-aligned telemetry and validation workflows.",
      ],
      tags: ["Time series", "Python", "Spark", "SQL", "MATLAB", "Telemetry"],
    },
    {
      company: "Rahbord Hooshmand",
      role: "Engineering Intern",
      location: "Tehran, Iran",
      period: "Jan 2018 — Dec 2020",
      logo: "/assets/images/rahbordhooshmand.png",
      summary: "Applying analytics and software development to smart-grid and operational data.",
      highlights: [
        "Used regression and Bayesian methods to analyze electrical and operational data.",
        "Developed modular C++ components for smart-grid telemetry systems.",
        "Built Power BI and Tableau dashboards for system performance decisions.",
      ],
      tags: ["C++", "Power BI", "Tableau", "Statistics", "Smart grid"],
    },
  ],
  education: [
    {
      school: "Polytechnique Montréal",
      degree: "M.A.Sc., Electrical Engineering",
      period: "2021 — 2024",
      logo: "/assets/images/polymtl.png",
      body: "Research at the intersection of grid systems, high-volume sensor telemetry, time-series processing, and machine learning.",
      href: "/assets/pdf/on-the-coordination-of-electric-water-heater-loads.pdf",
    },
    {
      school: "University of Tehran",
      degree: "B.Sc., Electrical Engineering",
      period: "2016 — 2021",
      logo: "/assets/images/UT.png",
      body: "Foundation in signal processing, control systems, numerical methods, circuits, and applied programming.",
    },
  ],
  certifications: [
    {
      title: "Data Analytics Specialization",
      issuer: "Google",
      date: "Nov 2024",
      logo: "/assets/images/google-logo.png",
      body: "Exploratory analysis, SQL, dashboards, and predictive modelling.",
      href: "/assets/pdf/coursera-google-data-analytics.pdf",
    },
    {
      title: "Neural Networks and Deep Learning",
      issuer: "DeepLearning.AI",
      date: "Nov 2024",
      logo: "/assets/images/deeplearning-ai-logo.png",
      body: "Forward/backward propagation, optimization, and deep neural networks.",
      href: "/assets/pdf/coursera-nn-and-dl.pdf",
    },
    {
      title: "Machine Learning Pipelines with Azure ML Studio",
      issuer: "Coursera Project Network",
      date: "Sep 2023",
      logo: "/assets/images/coursera-logo.png",
      body: "Preprocessing, model selection, deployment, and performance tracking.",
      href: "/assets/pdf/coursera-ml-with-azure.pdf",
    },
  ],
  awards: [
    { title: "Top 0.17% nationally", body: "Ranked 250th among more than 150,000 participants in Iran’s National University Entrance Exam." },
    { title: "Full graduate funding", body: "Awarded full research funding for the M.A.Sc. program at Polytechnique Montréal." },
    { title: "Project Day Award", body: "Recognized at the University of Tehran for residential energy-consumption modelling." },
  ],
};
